### ISSUE TITLE
Create blog post on calendar conversion

### ISSUE THREAD

**Issue by bonnland** [NCAR/xdev#102]
There is a draft pull request #87  around this right now. 

Questions: 

    1.   Should the post include a fully working example?
    2.  Should the topic include merging datasets with different calendars, or is this better as a separate, follow-on post?

**Comment by kmpaul** [comment]
> There is a draft pull request #87 around this right now.
> 
> Questions:
> 
> 1.  Should the post include a fully working example?

I would think the best thing would be a *minimal working example*.  Something *meaningful* as an educational example, but nothing so complex that the reader can't follow along without needing to take notes.

> 2.  Should the topic include merging datasets with different calendars, or is this better as a separate, follow-on post?

I think the answer to that depends on how complicated merging datasets with different calendars turns out to be.  I don't think a blog should take longer than 10-15 minutes to read, so I would assess based on that.

**Comment by kmpaul** [comment]
@bonnland:  I am in the process of archiving this old repository.  Do you want to transfer this issue to the ESDS blog or close it?  And what do you want to do about #87?

**Comment by bonnland** [comment]
Maybe in the future there will be more interest in cross-model comparisons, where this issue is potentially more important.   Right now it seems like there is not broad interest in this kind of topic, so it makes sense to close it until a later date.
